# Quiz 11 - Joins  
### Prinsa Ghimire

In this notebook, two related tables from the BigQuery public datasets will be explored and combined using a shared key. Different types of SQL joins will be implemented to understand how data from multiple tables can be merged. The notebook will demonstrate four join types: INNER JOIN, LEFT JOIN, RIGHT JOIN, and FULL OUTER JOIN. The results produced by each join will be examined and compared in order to understand how they differ and what type of records each join returns.

In [28]:
from google.colab import auth
auth.authenticate_user()
print('Authenticated')

Authenticated

Dataset used: `bigquery-public-data.stackoverflow`

Tables used:
- posts_questions
- posts_answers

The join key used in this notebook is:
posts_questions.id = posts_answers.parent_id

## Preview of Questions Table

The query below displays a sample of the `posts_questions` table.

In [27]:
%%bigquery --project quiz11-joins

SELECT *
FROM `bigquery-public-data.stackoverflow.posts_questions`
LIMIT 10;

Query is running:   0%|          |

Downloading:   0%|          |

,id,title,body,accepted_answer_id,answer_count,comment_count,community_owned_date,creation_date,favorite_count,last_activity_date,last_edit_date,last_editor_display_name,last_editor_user_id,owner_display_name,owner_user_id,parent_id,post_type_id,score,tags,view_count
0,54747762,how to save checkbox value after page load in ...,<p>How can I save the state of checked checkbo...,<NA>,3,0,NaT,2019-02-18 12:51:59.357000+00:00,<NA>,2019-03-18 10:55:50.130000+00:00,2019-03-18 10:55:50.130000+00:00,None,10279930,None,10279930,None,1,1,java|selenium|checkbox,256
1,54749260,ATM using data structure search arraylist of c...,<p>i create ATM and store customer data in arr...,54750769,2,0,NaT,2019-02-18 14:18:39.080000+00:00,<NA>,2019-02-18 15:45:34.243000+00:00,2019-02-18 15:45:34.243000+00:00,None,6579265,None,11056562,None,1,0,java|swing|stringbuilder,256
2,54768162,Integration test execution should wait until s...,<p>I have written Selenium tests which should ...,54956864,1,0,NaT,2019-02-19 14:05:53.007000+00:00,<NA>,2019-05-27 18:45:00.120000+00:00,2019-05-27 18:45:00.120000+00:00,None,9823031,None,9823031,None,1,0,maven|selenium|maven-tomcat-plugin,256
3,54770217,Install python package from local directory an...,<p>I've written a python package that I would ...,54770388,1,0,NaT,2019-02-19 15:52:36.303000+00:00,<NA>,2019-02-19 16:10:48.097000+00:00,NaT,None,<NA>,None,7926142,None,1,0,python|python-3.x|pip|python-packaging,256
4,54781815,count combination of columns in postgresql matrix,<p>I have a table in postgres like below</p>\n...,54783580,2,0,NaT,2019-02-20 08:26:44.777000+00:00,1,2019-02-20 17:47:04.673000+00:00,2019-02-20 08:27:51.303000+00:00,None,330315,None,11088704,None,1,1,sql|postgresql|matrix|combinations,256
5,54787520,Defining fr for grid only for first and second...,<p>I am creating a navigation for a website wi...,54787775,2,0,NaT,2019-02-20 13:31:17.487000+00:00,<NA>,2019-02-20 14:09:28.933000+00:00,2019-02-20 14:09:28.933000+00:00,None,6231153,None,11090271,None,1,2,html|css|css-grid,256
6,54791701,Featured image from custom to Wordpress database,<p>I want to adapt my old custom website datab...,<NA>,1,0,NaT,2019-02-20 17:00:11.810000+00:00,<NA>,2019-02-22 16:48:04.583000+00:00,2019-02-22 16:48:04.583000+00:00,None,1909673,None,1909673,None,1,0,mysql|database|wordpress,256
7,54796847,Dynamic URL across different environments usin...,<p>as a part of a requirement I have to config...,<NA>,2,0,NaT,2019-02-20 23:24:33.303000+00:00,1,2019-02-21 07:58:16.077000+00:00,NaT,None,<NA>,None,8417592,None,1,1,sap-commerce-cloud,256
8,54820707,Detect which tab we are in using CAPSPageMenu ...,<p>I am using CAPSPageMenu with 2 tabs. Now th...,54820787,2,0,NaT,2019-02-22 05:39:27.083000+00:00,<NA>,2019-02-22 08:34:17.543000+00:00,2019-02-22 06:34:51.803000+00:00,None,5203412,None,5203412,None,1,0,ios|objective-c|iphone|xcode|boolean,256
9,54844133,converting html+hex email address to readable ...,<p>I've been trying to find an online converte...,<NA>,1,0,NaT,2019-02-23 17:27:19.483000+00:00,<NA>,2019-02-23 19:32:16.983000+00:00,NaT,None,<NA>,None,7894473,None,1,0,python-3.x|hex|ascii|converters|email-address,256

## Preview of the Answers Table

The query below displays a sample of the `posts_answers` table.

In [26]:
%%bigquery --project quiz11-joins

SELECT *
FROM `bigquery-public-data.stackoverflow.posts_answers`
LIMIT 10;

Query is running:   0%|          |

Downloading:   0%|          |

,id,title,body,accepted_answer_id,answer_count,comment_count,community_owned_date,creation_date,favorite_count,last_activity_date,last_edit_date,last_editor_display_name,last_editor_user_id,owner_display_name,owner_user_id,parent_id,post_type_id,score,tags,view_count
0,67214823,None,"<p>there\nIf you want to use only PHP, then yo...",None,None,0,NaT,2021-04-22 14:02:18.487000+00:00,None,2021-04-22 14:02:18.487000+00:00,NaT,None,<NA>,None,12987235,67214173,2,0,None,None
1,67214829,None,"<p>I would put them into different subnets, We...",None,None,0,NaT,2021-04-22 14:02:30.260000+00:00,None,2021-04-22 14:17:41.057000+00:00,2021-04-22 14:17:41.057000+00:00,None,1100248,None,1100248,67214414,2,0,None,None
2,67214836,None,<p>Obtaining a Flux or a Mono does not necessa...,None,None,0,NaT,2021-04-22 14:03:25.970000+00:00,None,2021-04-22 14:08:46.050000+00:00,2021-04-22 14:08:46.050000+00:00,None,1839439,None,13858040,67179970,2,0,None,None
3,67214838,None,"<p>If you are willing to use a c# precompiler,...",None,None,0,NaT,2021-04-22 14:03:28.073000+00:00,None,2021-04-23 08:01:46.087000+00:00,2021-04-23 08:01:46.087000+00:00,None,6522669,None,6522669,731452,2,0,None,None
4,67214840,None,<p>Pass data from one screen to another and bu...,None,None,0,NaT,2021-04-22 14:03:40.740000+00:00,None,2021-04-22 14:03:40.740000+00:00,NaT,None,<NA>,None,2486969,67209199,2,0,None,None
5,67214845,None,<p>There are two things to know that were key ...,None,None,0,NaT,2021-04-22 14:03:57.377000+00:00,None,2021-04-22 14:03:57.377000+00:00,NaT,None,<NA>,None,4699368,67123207,2,0,None,None
6,67214850,None,<p>i had a similar problem and found that it w...,None,None,0,NaT,2021-04-22 14:04:13.320000+00:00,None,2021-04-22 14:04:13.320000+00:00,NaT,None,<NA>,None,8931319,64791065,2,0,None,None
7,67214852,None,<p>Dont use System ruby (the one in /Library/R...,None,None,0,NaT,2021-04-22 14:04:18.980000+00:00,None,2021-04-22 14:04:18.980000+00:00,NaT,None,<NA>,None,1901264,67206187,2,0,None,None
8,67214871,None,<p>I believe need to wait for the <code>connec...,None,None,0,NaT,2021-04-22 14:05:09.440000+00:00,None,2021-04-22 14:05:09.440000+00:00,NaT,None,<NA>,None,8454670,67214392,2,0,None,None
9,67214873,None,<p>I was able to solve this by creating and en...,None,None,0,NaT,2021-04-22 14:05:15.127000+00:00,None,2021-04-22 14:10:51.223000+00:00,2021-04-22 14:10:51.223000+00:00,None,9283274,None,9283274,33762181,2,0,None,None

## INNER JOIN

This query returns only questions that have matching answers.

In [25]:
%%bigquery --project quiz11-joins

SELECT
q.id AS question_id,
q.title,
a.id AS answer_id,
a.score
FROM `bigquery-public-data.stackoverflow.posts_questions` q
INNER JOIN `bigquery-public-data.stackoverflow.posts_answers` a
ON q.id = a.parent_id
LIMIT 10;

Query is running:   0%|          |

Downloading:   0%|          |

,question_id,title,answer_id,score
0,68175519,Is private key needed in Azure point to site VPN?,68176191,1
1,68398583,Why cant i implement NProgress in my Next.js App?,72930416,0
2,68273994,Python - Excel to HTML (keeping format),68538999,1
3,68290740,How to create flask server stub with either sw...,68290964,1
4,68345739,How to exclude Header while importing data fro...,68348938,0
5,68345739,How to exclude Header while importing data fro...,68349475,0
6,68441449,How to save an Outlook attachment to SharePoint?,68461753,0
7,68036007,How I disappear mat card when array is empty i...,68036137,1
8,68036007,How I disappear mat card when array is empty i...,68036170,1
9,68036007,How I disappear mat card when array is empty i...,68036158,2

## LEFT JOIN

This query returns all questions, even if they do not have answers.

In [24]:
%%bigquery --project quiz11-joins

SELECT
q.id AS question_id,
q.title,
a.id AS answer_id
FROM `bigquery-public-data.stackoverflow.posts_questions` q
LEFT JOIN `bigquery-public-data.stackoverflow.posts_answers` a
ON q.id = a.parent_id
LIMIT 10;

Query is running:   0%|          |

Downloading:   0%|          |

   question_id                                              title  answer_id
0     71431387  Implementing Previous Post & Next Post in a Ne...       <NA>
1     71431309  How to grab a DOM element in Next.js when clas...   71433192
2     71243750  Set Visual Studio Code settings.json across wo...       <NA>
3     71227017  Is it good to use TypeORM's entity models with...       <NA>
4     71217884  Android with Libgdx: cannot resolve symbol Goo...       <NA>
5     71253417  Kubernetes Network Policy - Allowing traffic t...   71259724
6     71349198  How do I add specific values of columns to cre...       <NA>
7     71442361       Recommendation for Code Analyzers for VB.Net       <NA>
8     71173548          How are users identified in LaunchDarkly?   71173549
9     71176332    Share a the weights of a series of Dense layers       <NA>

## RIGHT JOIN

This query returns all answers and their corresponding questions.

In [23]:
%%bigquery --project quiz11-joins

SELECT
q.id AS question_id,
q.title,
a.id AS answer_id
FROM `bigquery-public-data.stackoverflow.posts_questions` q
RIGHT JOIN `bigquery-public-data.stackoverflow.posts_answers` a
ON q.id = a.parent_id
LIMIT 10;

Query is running:   0%|          |

Downloading:   0%|          |

   question_id                                              title  answer_id
0     65210587              Discord.Net bot reply - contains word   65697888
1     65199813                 facebook messenger m.me share link   65248125
2     65283402  how to plot weekly time series data in r show ...   65283434
3     65077270  How to disable height property for table in re...   65095983
4     65164243  Passing today's date in soapui with specific f...   65165379
5     65129231  Webclient : java.lang.OutOfMemoryError: Direct...   65133879
6     65085775  Curl throwing a 400 Bad request error when usi...   65097929
7     65085775  Curl throwing a 400 Bad request error when usi...   65086610
8     65067907  In Kendo Master Detail Grid (jquery) is there ...   65074568
9     65158327  How can I save a networkD3::sankeyNetwork() in...   65159713

## FULL OUTER JOIN

This query returns all rows from both tables.

In [22]:
%%bigquery --project quiz11-joins

SELECT
q.id AS question_id,
q.title,
a.id AS answer_id
FROM `bigquery-public-data.stackoverflow.posts_questions` q
FULL OUTER JOIN `bigquery-public-data.stackoverflow.posts_answers` a
ON q.id = a.parent_id
LIMIT 10;

Query is running:   0%|          |

Downloading:   0%|          |

   question_id                                              title  answer_id
0     71263087            click/change event for formio component       <NA>
1     71120872   How to add a specific time period to indicators?   71122974
2     71194291  TypeError: Object(..) is not a function React-...   71194520
3     71194291  TypeError: Object(..) is not a function React-...   71194361
4     71194291  TypeError: Object(..) is not a function React-...   71194648
5     71125866                     Spring Mongo DocumentReference   71525384
6     71131703  How do I handle a series of pipe delimited val...       <NA>
7     71246940            Firebase analytics duplicated event log       <NA>
8     71266686  Simplify over-complex Django filter/list/np.ar...       <NA>
9     71131595       Rolling windows for a 1D array with big siye       <NA>